#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new MakeTestCommand());
$application->add(new MakeCommandCommand());
$application->add(new MakeTestCommand());

try {
    $application->run();
} catch (Exception $e) {
    dump('Se ha producido un error: ' . $e->getMessage());
}
